default-resources:
    slurm_partition: "cafe"
    slurm_account: "cafe"
    runtime: "1h"
jobs: 192
executor: slurm
use-apptainer: true
apptainer-args: "--home $PWD/.."
# latency-wait: 10
rerun-incomplete: true
