default-resources:
    slurm_partition: "cafe-lo"
    slurm_account: "cafe"
    runtime: "1h"
    slurm_extra: "'--nice=343 --hint=nomultithread'"
jobs: 192
executor: slurm
use-apptainer: true
apptainer-args: "--home /cafe/u/nmosier"
latency-wait: 60
rerun-incomplete: true
